--------------------------------------------------------
--  File created - среда-окт€бр€-28-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSPORTER
--------------------------------------------------------

  CREATE TABLE "LAB2_USER"."TRANSPORTER" 
   (	"TRANSPORTER_ID" NUMBER, 
	"TRANSPORTER_NAME" CHAR(20 BYTE), 
	"INTERNETIONAL_CODE" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LAB2_USER.TRANSPORTER
SET DEFINE OFF;
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('1','Fly Emirates        ','AA   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('2','S7 Airlines         ','AB   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('3','Boing               ','AC   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('4','Pobeda              ','AD   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('5','Airflot             ','AE   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('6','China Air           ','AF   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('7','Air India           ','BA   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('8','Canada airlines     ','BB   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('9','Arkia               ','BC   ');
Insert into LAB2_USER.TRANSPORTER (TRANSPORTER_ID,TRANSPORTER_NAME,INTERNETIONAL_CODE) values ('10','IndiGo              ','BD   ');
--------------------------------------------------------
--  DDL for Index TRANSPORTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LAB2_USER"."TRANSPORTER_PK" ON "LAB2_USER"."TRANSPORTER" ("TRANSPORTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TRANSPORTER
--------------------------------------------------------

  ALTER TABLE "LAB2_USER"."TRANSPORTER" ADD CONSTRAINT "TRANSPORTER_PK" PRIMARY KEY ("TRANSPORTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LAB2_USER"."TRANSPORTER" MODIFY ("INTERNETIONAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "LAB2_USER"."TRANSPORTER" MODIFY ("TRANSPORTER_ID" NOT NULL ENABLE);
